# Generated by Django 4.1.1 on 2022-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
    ]
