# Generated by Django 4.1.1 on 2022-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_controller', '0002_message_is_ignore_purchase_is_ignore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='amount_returned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
